version: '3'
services:
  web:
    command: ["sh", "./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "python", "docker_quickstart.py"]
    image: instagramtools/web
    environment:
      - PYTHONUNBUFFERED=0
      - SELENIUM=selenium
      - API="http://localhost:8000/api/bot"
      - PROXY_MANAGER=http://proxy-manager:60000
    build: .
    depends_on:
      - selenium
      - proxy-manager
    links:
      - selenium:selenium
      - proxy-manager:proxy-manager
    volumes:
      - ./logs:/code/logs


  proxy-manager:
    image: gott50/proxy-manager
    ports:
      - 60000:60000
    environment:
      - DEBUG=False
    env_file:
      - .env/.proxy-manager.env

  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    ports:
      - "5900:5900"
      - "4444:4444"
    shm_size: 128M
